// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/input.

#pragma once

#include <VoxelEngine/input/input_binder.hpp>
#include <VoxelEngine/input/input_event.hpp>
#include <VoxelEngine/input/input_manager.hpp>
#include <VoxelEngine/input/keyboard.hpp>
#include <VoxelEngine/input/mouse.hpp>
#include <VoxelEngine/input/window.hpp>
