// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/utility/serialize.

#pragma once

#include <VoxelEngine/utility/serialize/auto_binary_serializable.hpp>
#include <VoxelEngine/utility/serialize/auto_binary_serializers.hpp>
#include <VoxelEngine/utility/serialize/binary_serializable.hpp>
#include <VoxelEngine/utility/serialize/externally_serializable.hpp>
#include <VoxelEngine/utility/serialize/serialization_utils.hpp>
#include <VoxelEngine/utility/serialize/string_serializable.hpp>
