// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/utility/traits.

#pragma once

#include <VoxelEngine/utility/traits/always_false.hpp>
#include <VoxelEngine/utility/traits/bind.hpp>
#include <VoxelEngine/utility/traits/const_as.hpp>
#include <VoxelEngine/utility/traits/dont_deduce.hpp>
#include <VoxelEngine/utility/traits/evaluate_if_valid.hpp>
#include <VoxelEngine/utility/traits/function_traits.hpp>
#include <VoxelEngine/utility/traits/glm_traits.hpp>
#include <VoxelEngine/utility/traits/is_immovable.hpp>
#include <VoxelEngine/utility/traits/is_std_array.hpp>
#include <VoxelEngine/utility/traits/is_template.hpp>
#include <VoxelEngine/utility/traits/is_type.hpp>
#include <VoxelEngine/utility/traits/maybe_const.hpp>
#include <VoxelEngine/utility/traits/member_traits.hpp>
#include <VoxelEngine/utility/traits/negate_trait.hpp>
#include <VoxelEngine/utility/traits/nest.hpp>
#include <VoxelEngine/utility/traits/null_type.hpp>
#include <VoxelEngine/utility/traits/pack/pack.hpp>
#include <VoxelEngine/utility/traits/pack/pack_helpers.hpp>
#include <VoxelEngine/utility/traits/pack/pack_ops.hpp>
#include <VoxelEngine/utility/traits/pick.hpp>
#include <VoxelEngine/utility/traits/ratio.hpp>
#include <VoxelEngine/utility/traits/reference_as.hpp>
#include <VoxelEngine/utility/traits/remove_const_pointer.hpp>
#include <VoxelEngine/utility/traits/sequence.hpp>
#include <VoxelEngine/utility/traits/string_arg.hpp>
#include <VoxelEngine/utility/traits/value.hpp>
