// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/utility/traits.

#pragma once

#include <VoxelEngine/utility/traits/always_false.hpp>
#include <VoxelEngine/utility/traits/any_of.hpp>
#include <VoxelEngine/utility/traits/glm_traits.hpp>
#include <VoxelEngine/utility/traits/is_of_template.hpp>
#include <VoxelEngine/utility/traits/maybe_const.hpp>
#include <VoxelEngine/utility/traits/member_function_traits.hpp>
#include <VoxelEngine/utility/traits/null_type.hpp>
#include <VoxelEngine/utility/traits/pack.hpp>
#include <VoxelEngine/utility/traits/pick.hpp>
#include <VoxelEngine/utility/traits/reference_as.hpp>
#include <VoxelEngine/utility/traits/streamable.hpp>
#include <VoxelEngine/utility/traits/string_arg.hpp>
#include <VoxelEngine/utility/traits/this_type.hpp>
#include <VoxelEngine/utility/traits/type_categories.hpp>
