// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/ecs.

#pragma once

#include <VoxelEngine/ecs/component/component.hpp>
#include <VoxelEngine/ecs/component/function_component.hpp>
#include <VoxelEngine/ecs/component/function_registry.hpp>
#include <VoxelEngine/ecs/component/named_component.hpp>
#include <VoxelEngine/ecs/component/renderable_component.hpp>
#include <VoxelEngine/ecs/component/static_component.hpp>
#include <VoxelEngine/ecs/component/static_component_info.hpp>
#include <VoxelEngine/ecs/component/transform_component.hpp>
#include <VoxelEngine/ecs/component/value_component.hpp>
#include <VoxelEngine/ecs/entity/entity.hpp>
#include <VoxelEngine/ecs/entity/entity_group.hpp>
#include <VoxelEngine/ecs/scene.hpp>
#include <VoxelEngine/ecs/scene_registry.hpp>
#include <VoxelEngine/ecs/system/renderer.hpp>
#include <VoxelEngine/ecs/system/system.hpp>
#include <VoxelEngine/ecs/system/system_view_type.hpp>
