// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/ecs.

#pragma once

#include <VoxelEngine/ecs/change_validator.hpp>
#include <VoxelEngine/ecs/component/component_tags.hpp>
#include <VoxelEngine/ecs/component/function_component.hpp>
#include <VoxelEngine/ecs/component/light_component.hpp>
#include <VoxelEngine/ecs/component/mesh_component.hpp>
#include <VoxelEngine/ecs/component/motion_component.hpp>
#include <VoxelEngine/ecs/component/named_component.hpp>
#include <VoxelEngine/ecs/component/partially_synchronizable.hpp>
#include <VoxelEngine/ecs/component/raii_component.hpp>
#include <VoxelEngine/ecs/component/self_component.hpp>
#include <VoxelEngine/ecs/component/transform_component.hpp>
#include <VoxelEngine/ecs/component/voxel_component.hpp>
#include <VoxelEngine/ecs/component_registry.hpp>
#include <VoxelEngine/ecs/entity/static_component.hpp>
#include <VoxelEngine/ecs/entity/static_entity.hpp>
#include <VoxelEngine/ecs/registry.hpp>
#include <VoxelEngine/ecs/registry_helpers.hpp>
#include <VoxelEngine/ecs/system/system.hpp>
#include <VoxelEngine/ecs/system/system_entity_visibility.hpp>
#include <VoxelEngine/ecs/system/system_physics.hpp>
#include <VoxelEngine/ecs/system/system_remote_initializer.hpp>
#include <VoxelEngine/ecs/system/system_renderer.hpp>
#include <VoxelEngine/ecs/system/system_synchronizer.hpp>
#include <VoxelEngine/ecs/system/system_updater.hpp>
#include <VoxelEngine/ecs/view.hpp>
