// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/ecs.

#pragma once

#include <VoxelEngine/ecs/entity/group.hpp>
#include <VoxelEngine/ecs/entity/static_entity.hpp>
#include <VoxelEngine/ecs/system/system.hpp>
#include <VoxelEngine/ecs/view_type.hpp>
