// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/platform/graphics/vulkan.

#pragma once

#include <VoxelEngine/platform/graphics/vulkan/common.hpp>
#include <VoxelEngine/platform/graphics/vulkan/resource.hpp>
#include <VoxelEngine/platform/graphics/vulkan/vulkan_helpers.hpp>
#include <VoxelEngine/platform/graphics/vulkan/window/window_details.hpp>
