// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/voxel.

#pragma once

#include <VoxelEngine/voxel/chunk/chunk.hpp>
#include <VoxelEngine/voxel/chunk/chunk_mesher.hpp>
#include <VoxelEngine/voxel/chunk/generator/generator.hpp>
#include <VoxelEngine/voxel/chunk/generator/noise_generator.hpp>
#include <VoxelEngine/voxel/chunk/generator/world_layers.hpp>
#include <VoxelEngine/voxel/chunk/loader.hpp>
#include <VoxelEngine/voxel/settings.hpp>
#include <VoxelEngine/voxel/space/voxel_space.hpp>
#include <VoxelEngine/voxel/tile/tile.hpp>
#include <VoxelEngine/voxel/tile/tile_data.hpp>
#include <VoxelEngine/voxel/tile/tile_registry.hpp>
#include <VoxelEngine/voxel/tile/tiles.hpp>
#include <VoxelEngine/voxel/tile_provider.hpp>
