// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/graphics/texture/utility.

#pragma once

#include <VoxelEngine/graphics/texture/utility/combine.hpp>
#include <VoxelEngine/graphics/texture/utility/combine_material.hpp>
#include <VoxelEngine/graphics/texture/utility/convert.hpp>
#include <VoxelEngine/graphics/texture/utility/luma.hpp>
#include <VoxelEngine/graphics/texture/utility/resize.hpp>
#include <VoxelEngine/graphics/texture/utility/sampler.hpp>
#include <VoxelEngine/graphics/texture/utility/to_grayscale.hpp>
