// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/tests/framework.

#pragma once

#include <VoxelEngine/tests/framework/callbacks.hpp>
#include <VoxelEngine/tests/framework/framework_core.hpp>
#include <VoxelEngine/tests/framework/framework_utils.hpp>
