// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/core.

#pragma once

#include <VoxelEngine/core/codegen/builtins.hpp>
#include <VoxelEngine/core/codegen/comparison.hpp>
#include <VoxelEngine/core/codegen/crtp.hpp>
#include <VoxelEngine/core/codegen/getter_setter.hpp>
#include <VoxelEngine/core/codegen/move_only.hpp>
#include <VoxelEngine/core/codegen/mute_warning.hpp>
#include <VoxelEngine/core/codegen/wrapper.hpp>
#include <VoxelEngine/core/definitions/aliases.hpp>
#include <VoxelEngine/core/definitions/c_syntax.hpp>
#include <VoxelEngine/core/definitions/container.hpp>
#include <VoxelEngine/core/definitions/hash.hpp>
#include <VoxelEngine/core/definitions/pointer.hpp>
#include <VoxelEngine/core/definitions/scalar.hpp>
#include <VoxelEngine/core/definitions/tensor.hpp>
#include <VoxelEngine/core/definitions/type_id.hpp>
#include <VoxelEngine/core/doxygen.hpp>
#include <VoxelEngine/core/ioc.hpp>
#include <VoxelEngine/core/platform.hpp>
#include <VoxelEngine/core/preprocessor.hpp>
