// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/core.

#pragma once

#include <VoxelEngine/core/alloca_support.hpp>
#include <VoxelEngine/core/breakpoint.hpp>
#include <VoxelEngine/core/codegen/arithmetic.hpp>
#include <VoxelEngine/core/codegen/bitwise_enum.hpp>
#include <VoxelEngine/core/codegen/compare.hpp>
#include <VoxelEngine/core/codegen/crtp.hpp>
#include <VoxelEngine/core/codegen/dereference.hpp>
#include <VoxelEngine/core/codegen/hash.hpp>
#include <VoxelEngine/core/codegen/move.hpp>
#include <VoxelEngine/core/codegen/mutator.hpp>
#include <VoxelEngine/core/codegen/not_yet_implemented.hpp>
#include <VoxelEngine/core/codegen/shared_only.hpp>
#include <VoxelEngine/core/codegen/symbol_export.hpp>
#include <VoxelEngine/core/codegen/unreachable.hpp>
#include <VoxelEngine/core/codegen/wrap_container.hpp>
#include <VoxelEngine/core/includes.hpp>
#include <VoxelEngine/core/legacy.hpp>
#include <VoxelEngine/core/overridable_fn_tag.hpp>
#include <VoxelEngine/core/platform.hpp>
#include <VoxelEngine/core/preprocessor.hpp>
#include <VoxelEngine/core/profiler.hpp>
#include <VoxelEngine/core/range.hpp>
#include <VoxelEngine/core/settings_preinclude.hpp>
#include <VoxelEngine/core/typedef/chrono.hpp>
#include <VoxelEngine/core/typedef/container.hpp>
#include <VoxelEngine/core/typedef/function.hpp>
#include <VoxelEngine/core/typedef/glm.hpp>
#include <VoxelEngine/core/typedef/pointer.hpp>
#include <VoxelEngine/core/typedef/scalar.hpp>
#include <VoxelEngine/core/windows_header_cleanup.hpp>
