// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/core.

#pragma once

#include <VoxelEngine/core/assert.hpp>
#include <VoxelEngine/core/configuration.hpp>
#include <VoxelEngine/core/mutator.hpp>
#include <VoxelEngine/core/preprocessor.hpp>
#include <VoxelEngine/core/traits.hpp>
#include <VoxelEngine/core/typedefs/constants.hpp>
#include <VoxelEngine/core/typedefs/container.hpp>
#include <VoxelEngine/core/typedefs/glm.hpp>
#include <VoxelEngine/core/typedefs/legacy.hpp>
#include <VoxelEngine/core/typedefs/misc.hpp>
#include <VoxelEngine/core/typedefs/namespace.hpp>
#include <VoxelEngine/core/typedefs/operator.hpp>
#include <VoxelEngine/core/typedefs/scalar.hpp>
