// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/graphics.

#pragma once

#include <VoxelEngine/graphics/buffer/multi_buffer.hpp>
#include <VoxelEngine/graphics/camera/perspective_camera.hpp>
#include <VoxelEngine/graphics/mesh/voxel_mesher.hpp>
#include <VoxelEngine/graphics/mesh/voxel_mesher_helpers.hpp>
#include <VoxelEngine/graphics/shader_buffer_pair.hpp>
#include <VoxelEngine/graphics/texture/aligned_texture_atlas.hpp>
#include <VoxelEngine/graphics/texture/generative_texture_atlas.hpp>
#include <VoxelEngine/graphics/texture/texture_atlas.hpp>
#include <VoxelEngine/graphics/texture/texture_manager.hpp>
#include <VoxelEngine/graphics/window/layerstack.hpp>
#include <VoxelEngine/graphics/window/window.hpp>
#include <VoxelEngine/graphics/window/window_registry.hpp>
