// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/graphics.

#pragma once

#include <VoxelEngine/graphics/camera/camera_uniform.hpp>
#include <VoxelEngine/graphics/camera/perspective_camera.hpp>
#include <VoxelEngine/graphics/presentation/present_mode.hpp>
#include <VoxelEngine/graphics/presentation/window.hpp>
#include <VoxelEngine/graphics/presentation/window_registry.hpp>
#include <VoxelEngine/graphics/shader/cache.hpp>
#include <VoxelEngine/graphics/shader/compiler.hpp>
#include <VoxelEngine/graphics/shader/glsl_layout.hpp>
#include <VoxelEngine/graphics/shader/include_handler.hpp>
#include <VoxelEngine/graphics/shader/layout_validator.hpp>
#include <VoxelEngine/graphics/shader/object_type.hpp>
#include <VoxelEngine/graphics/shader/reflect.hpp>
#include <VoxelEngine/graphics/texture/aligned_texture_atlas.hpp>
#include <VoxelEngine/graphics/texture/generative_texture_atlas.hpp>
#include <VoxelEngine/graphics/texture/texture_atlas.hpp>
#include <VoxelEngine/graphics/uniform/uniform_combine_function.hpp>
#include <VoxelEngine/graphics/uniform/uniform_convertible.hpp>
#include <VoxelEngine/graphics/vertex/vertex.hpp>
