// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/platform/graphics/opengl.

#pragma once

#include <VoxelEngine/platform/graphics/opengl/context/api_context.hpp>
#include <VoxelEngine/platform/graphics/opengl/context/render_context.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/category.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/framebuffer.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/multipass_pbr_pipeline.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/pipeline.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/settings.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/target.hpp>
#include <VoxelEngine/platform/graphics/opengl/presentation/canvas.hpp>
#include <VoxelEngine/platform/graphics/opengl/presentation/window_helpers.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/shader.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/shader_helpers.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/stage.hpp>
#include <VoxelEngine/platform/graphics/opengl/texture/format.hpp>
#include <VoxelEngine/platform/graphics/opengl/texture/texture.hpp>
#include <VoxelEngine/platform/graphics/opengl/uniform/uniform.hpp>
#include <VoxelEngine/platform/graphics/opengl/uniform/uniform_bind_state.hpp>
#include <VoxelEngine/platform/graphics/opengl/uniform/uniform_buffer.hpp>
#include <VoxelEngine/platform/graphics/opengl/uniform/uniform_storage.hpp>
#include <VoxelEngine/platform/graphics/opengl/utility/buffer.hpp>
#include <VoxelEngine/platform/graphics/opengl/utility/debug.hpp>
#include <VoxelEngine/platform/graphics/opengl/utility/get.hpp>
#include <VoxelEngine/platform/graphics/opengl/utility/resource.hpp>
#include <VoxelEngine/platform/graphics/opengl/vertex/layout.hpp>
#include <VoxelEngine/platform/graphics/opengl/vertex/vertex_buffer.hpp>
