// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes all headers in VoxelEngine/platform/graphics/opengl.

#pragma once

#include <VoxelEngine/platform/graphics/opengl/buffer/attribute.hpp>
#include <VoxelEngine/platform/graphics/opengl/buffer/buffer.hpp>
#include <VoxelEngine/platform/graphics/opengl/buffer/buffer_settings.hpp>
#include <VoxelEngine/platform/graphics/opengl/buffer/buffer_utils.hpp>
#include <VoxelEngine/platform/graphics/opengl/buffer/indexed_vertex_buffer.hpp>
#include <VoxelEngine/platform/graphics/opengl/buffer/vertex.hpp>
#include <VoxelEngine/platform/graphics/opengl/buffer/vertex_buffer.hpp>
#include <VoxelEngine/platform/graphics/opengl/common.hpp>
#include <VoxelEngine/platform/graphics/opengl/context.hpp>
#include <VoxelEngine/platform/graphics/opengl/error_callback.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/pipeline.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/shader_program.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/spirv_to_gl_shader.hpp>
#include <VoxelEngine/platform/graphics/opengl/target/framebuffer_target.hpp>
#include <VoxelEngine/platform/graphics/opengl/target/layerstack_target.hpp>
#include <VoxelEngine/platform/graphics/opengl/target/target.hpp>
#include <VoxelEngine/platform/graphics/opengl/texture/format.hpp>
#include <VoxelEngine/platform/graphics/opengl/texture/texture.hpp>
#include <VoxelEngine/platform/graphics/opengl/texture/texture_loader.hpp>
#include <VoxelEngine/platform/graphics/opengl/texture/texture_utils.hpp>
#include <VoxelEngine/platform/graphics/opengl/uniform/set_uniform.hpp>
#include <VoxelEngine/platform/graphics/opengl/uniform/uniform_storage.hpp>
#include <VoxelEngine/platform/graphics/opengl/window/window_details.hpp>
