// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/platform/graphics/opengl.

#pragma once

#include <VoxelEngine/platform/graphics/opengl/context/api_context.hpp>
#include <VoxelEngine/platform/graphics/opengl/pipeline/category.hpp>
#include <VoxelEngine/platform/graphics/opengl/presentation/canvas.hpp>
#include <VoxelEngine/platform/graphics/opengl/presentation/window_helpers.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/shader.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/shader_helpers.hpp>
#include <VoxelEngine/platform/graphics/opengl/shader/stage.hpp>
#include <VoxelEngine/platform/graphics/opengl/utility/resource.hpp>
