// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VoxelEngine/event.

#pragma once

#include <VoxelEngine/event/delayed_event_dispatcher.hpp>
#include <VoxelEngine/event/dispatcher.hpp>
#include <VoxelEngine/event/event_handler_id.hpp>
#include <VoxelEngine/event/simple_event_dispatcher.hpp>
#include <VoxelEngine/event/subscribe_only_view.hpp>
