// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from VEDemoPlugin/core.

#pragma once

#include <VEDemoPlugin/core/api.hpp>
