name: VoxelEngine CI

# Temporarily only apply to CI branch for testing. This should be replaced with 
# on:
#   push:
#     branches: ['**']
#   pull-request:
#     branches: [master]
on:
  push:
    branches: [ci]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: log_msvc_dir
      run: |
        C:
        cd "C:\Program Files (x86)\Windows Kits\10\Lib\"
        dir -s 
    - uses: actions/checkout@v2
    - name: configure
      run: |
        choco install ninja cmake python -y
        choco install visualstudio2022buildtools --version 117.1.2.0 -y
        choco install llvm --version 14.0.0 -y
        pip install conan
        mkdir out
    - name: run cmake
      working-directory: ./out
      run: |
        cmake -DCMAKE_BUILD_TYPE=DEBUG -G Ninja -DVE_GRAPHICS_API=opengl -DENABLE_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl ../
    - name: build
      working-directory: ./out
      run: |
        cmake --build ./debug --target all
    - name: engine test run
      working-directory: ./out/debug/bin
      run: VELauncher --client --server --run_for=100
    - name: run unit tests
      working-directory: ./out/debug
      run: ctest --extra-verbose
