name: VoxelEngine CI

# Temporarily only apply to CI branch for testing. This should be replaced with 
# on:
#   push:
#     branches: ['**']
#   pull-request:
#     branches: [master]
on:
  push:
    branches: [ci]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
        choco install ninja cmake python visualstudio2019buildtools -y --no-progress
        choco install llvm --version 14.0.0 -y --no-progress
        pip install conan --progress-bar off
        mkdir out
        refreshenv
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Run CMake
      working-directory: ./out
      run: >
        cmake 
        -DCMAKE_BUILD_TYPE=DEBUG 
        -G Ninja 
        -DCMAKE_C_COMPILER_WORKS=ON
        -DCMAKE_CXX_COMPILER_WORKS=ON
        -DVE_GRAPHICS_API=opengl 
        -DENABLE_TESTING=ON 
        -DCMAKE_VERBOSE_MAKEFILE=ON 
        -DCMAKE_C_COMPILER=clang-cl 
        -DCMAKE_CXX_COMPILER=clang-cl 
        ../
    - name: Build
      working-directory: ./out
      run: |
        cmake --build ./debug --target all
    - name: Engine test run
      working-directory: ./out/debug/bin
      run: VELauncher --client --server --run_for=100
    - name: Run unit tests
      working-directory: ./out/debug
      run: ctest --extra-verbose
